In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris=load_iris()

In [5]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [6]:
from sklearn.model_selection import cross_val_score

In [9]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [10]:
cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [12]:
cross_val_score(RandomForestClassifier(n_estimators=30),iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.94])

In [13]:
cross_val_score(DecisionTreeClassifier(),iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.98])

In [14]:
score1=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)
np.average(score1)

0.9533333333333333

In [15]:
score2=cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=3)
np.average(score2)

0.9733333333333333

In [16]:
score3=cross_val_score(RandomForestClassifier(n_estimators=30),iris.data,iris.target,cv=3)
np.average(score3)

0.9666666666666667

In [17]:
score4=cross_val_score(DecisionTreeClassifier(),iris.data, iris.target,cv=3)
np.average(score4)

0.9666666666666667